Implement Service to Create Opensearch Indexes of Artifacts
hotwax/artifactLifeCycle pull request #6
Opened 2024-11-28 04:49 UTC by puru-khedre

I've Implemented the below services
### 1. `consume#AllArtifactLogs`: (wrapper service)
This service lists all the newly updated artifact logs and calls the core service to create indexes of artifacts

### 2. `create#ArtifactLogIndex`: (core service)
Core service to create an index of a single artifact log, this service handles the content based on the content file format

2024-11-28 08:54 UTC, dt2patel requested changes
See suggested commits as well as revise based on design discussion we had in respect to how the core indexing service should function.

2024-11-28 08:54 UTC, dt2patel commented on service/co/hotwax/alc/ArtifactLifeCycleServices.xml
> +        <description>This service processes the provided artifact log and creates an index on opensearch.</description>
```suggestion
        <description>This service processes the provided Artifact Log and creates an index on OpenSearch.</description>
```

2024-11-28 08:54 UTC, dt2patel commented on service/co/hotwax/alc/ArtifactLifeCycleServices.xml
> +            <parameter name="artifactLogValue" type="Map"/>
This service should only accept event Id not a map. event ID is required

2024-11-28 08:54 UTC, dt2patel commented on service/co/hotwax/alc/ArtifactLifeCycleServices.xml
> +                    ec.message.addError("File Format ${contentType} is not Supported")
```suggestion
                    ec.message.addError("${contentType} file format is not supported. Please upload a JSON or CSV")
```

2024-11-28 13:56 UTC, puru-khedre commented
@dt2patel sir, We can merge this PR now all comments have been resolved

Creating a separate PR to Implement the Artifact Logs create service

2024-11-28 14:33 UTC, dt2patel requested changes
Update naming

2024-11-28 14:33 UTC, dt2patel commented on service/co/hotwax/alc/ArtifactLifeCycleServices.xml
> +            <iterate list="artifactLogList" entry="artifactLogValue">
```suggestion
            <iterate list="artifactLogList" entry="artifactEvent">
```

2024-11-28 14:33 UTC, dt2patel commented on service/co/hotwax/alc/ArtifactLifeCycleServices.xml
> +                <service-call name="co.hotwax.alc.ArtifactLifeCycleServices.create#ArtifactLogIndex" in-map="[artifactEventId:artifactLogValue.artifactEventId]"/>
```suggestion
                <service-call name="co.hotwax.alc.ArtifactLifeCycleServices.create#ArtifactLogIndex" in-map="[artifactEventId:artifactEvent.artifactEventId]"/>
```

2024-11-28 14:33 UTC, dt2patel commented on service/co/hotwax/alc/ArtifactLifeCycleServices.xml
> +            <return message="Total ${createIndexCount} Artifact Logs are indexed that are updated after Datetime: ${sinceDate}"/>
```suggestion
            <return message="${createIndexCount} Artifact Logs were indexed from ${sinceDate}"/>
```

2024-11-28 14:33 UTC, dt2patel commented on service/co/hotwax/alc/ArtifactLifeCycleServices.xml
> +            <entity-find-one entity-name="co.hotwax.alc.ArtifactLog" value-field="artifactLogValue"/>
```suggestion
            <entity-find-one entity-name="co.hotwax.alc.ArtifactLog" value-field="artifactLog"/>
```

2024-11-28 14:33 UTC, dt2patel commented on service/co/hotwax/alc/ArtifactLifeCycleServices.xml
> +            <if condition="artifactLogValue == null"><return error="true" message="Artifact Log is not found"/></if>
```suggestion
            <if condition="artifactLog == null"><return error="true" message="Artifact Log is not found"/></if>
```

2024-12-02 06:12 UTC, dt2patel requested changes

2024-12-02 06:12 UTC, dt2patel commented on data/ArtifactLogServiceJobData.xml
> +            description="consume all of the newly created Artifact Logs"
```suggestion
            description="Index recently updated Artifact Logs"
```

2024-12-02 06:12 UTC, dt2patel commented on service/co/hotwax/alc/ArtifactLifeCycleServices.xml
> +                <description>The timestamp to filter artifact logs updated after this date</description>
```suggestion
                <description>Filter Artifact Logs updated after this date time</description>
```

2024-12-02 13:23 UTC, dt2patel approved these changes

2024-12-02 13:29 UTC, merged